language: node_js

node_js:
  - "10"
  - "12"
  - "13"

branches:
  only:
    - master

install:
  # Fail if lockfile outdated.
  # https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile
  - yarn install --frozen-lockfile

script:
  - yarn --version
  - yarn run clean
  - yarn run build-lib --sourcemap
  - yarn run test-cli
  - yarn run build-test
  - yarn run check-ci
  - codecov
