language: node_js

node_js:
  - "6"
  - "8"
  - "10"

branches:
  only:
    - master

install:
  # Fail if lockfile outdated.
  # https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile
  - yarn install --frozen-lockfile

script:
  - yarn --version
  - yarn run build
  - yarn run build-test
  - yarn run check-ci
  # Upload to coveralls, but don't _fail_ if coveralls is down.
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || echo "Coveralls upload failed"
