environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    # `mock-fs` doesn't support `node@10.5+`
    # https://github.com/FormidableLabs/inspectpack/issues/83
    - nodejs_version: "10.4"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

# Post-install test scripts.
test_script:
  - node --version
  - yarn --version
  - yarn run build
  - yarn run build-test
  - yarn run check

# Don't actually build.
build: off

matrix:
  fast_finish: true

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"
