environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:node_version
  - yarn install

# Post-install test scripts.
test_script:
  - yarn --version
  - yarn run build
  - yarn run build-test
  - yarn run check

# Don't actually build.
build: off

matrix:
  fast_finish: true

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"
