"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var base_1 = require("./actions/base");
exports.TemplateFormat = base_1.TemplateFormat;
var actions_1 = require("./actions");
exports.ACTIONS = actions_1.ACTIONS;
exports.actions = actions_1.actions;
exports.render = actions_1.render;
var files_1 = require("./util/files");
exports.readJson = files_1.readJson;
