name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    # Setup
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Installation
    - run: yarn --version
    - run: yarn install --frozen-lockfile
      env:
        CI: true

    # Build lib
    - run: yarn clean
    - run: yarn build-lib --sourcemap

    # Basic CLI test
    - run: yarn test-usage

    # Full tests
    - run: yarn build-test
    - run: yarn check # TODO: UNWIND
    - run: yarn codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
